### ISSUE TITLE
Sample feed url returns nothing

### ISSUE THREAD

**Issue by LeonB** [trustpilot/developers#27]
The sample feed mentioned on https://trustpilot.github.io/developers/ (http://s.trustpilot.com/tpelements/917278/f.json.gz) doesn't return any data anymore.

I tried a live url for a client of ours (`"https://ssl.trustpilot.com/tpelements/{$domainId}/f.json.gz"` and that also doesn't return any data.

**Comment by dallerup** [comment]
Sorry, we are discontinue the json feed and replacing it with our new apis. 
I would recommend taking a look at the documentation below instead as they provide much richer possibilities to building your applications.

https://apps.trustpilot.com/
https://apps.trustpilot.com/introduction

**Comment by toin0u** [comment]
Thanks for your answer :)

When does the JSON feed will be 100% discontinued ?

**Comment by dallerup** [comment]
There is not date yet but a guess is within 3 months, so you still have time if you are using the json feed. 
We will be sure to inform you when time is.
I can also highly recommend to look at our Trustboxes https://support.trustpilot.com/hc/en-gb/articles/204123713-TrustBox-Library-
This way you avoid to apply to the integration guidelines, but it of cause depends on your use case.
https://support.trustpilot.com/hc/en-gb/articles/202319278-Integration-Guidelines

**Comment by toin0u** [comment]
@dallerup Thanks :)

I actually don't use Trustpilot but I maintain a PHP library:
> https://packagist.org/search/?q=trustpilot
> https://packagist.org/packages/toin0u/trustpilot

I'll update the library when I'll get the chance :) I think 3 months sounds reasonable though!

**Comment by dallerup** [comment]
Sure no problem happy to see that. We will as time go publish more apis, with more possibilities.

**Comment by LeonB** [comment]
@dallerup thanks for the reply. I'll have a look at the new api.
